# Generated by Django 5.0.4 on 2024-08-23 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_district_upozilla_addressjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressjob',
            name='amount_payable',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='addressjob',
            name='category_of_membership',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='addressjob',
            name='company_name',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='addressjob',
            name='designation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='addressjob',
            name='highest_degree_obtained',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='addressjob',
            name='mobile',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='addressjob',
            name='occupation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='addressjob',
            name='telephone',
            field=models.CharField(max_length=14, null=True),
        ),
    ]
