# Generated by Django 5.0.4 on 2024-08-24 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_addressjob_amount_payable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressjob',
            name='mobile',
            field=models.CharField(default='00000000000', max_length=11),
        ),
    ]
